### ISSUE TITLE
Lastest version for UWP won't install

### ISSUE THREAD

**Issue by elwardrm** [Azure-Samples/MyDriving#495]
I'm trying to upgrade to the latest version(1.0.0.391 ) of the UWP app.  I've downloaded it and get the prompt asking me if I want to install it but when I press the Install button nothing happens.  I'm using a Nokia 635 phone with Windows 10 Mobile (10.0.10586.107).  I have a version running on the phone so I assume that the developer certificate and three other dependent libraries are installed.

Do I have to uninstall the app first?

**Comment by VaijanathA** [comment]
Hello elwardrm,

The apps installed with HockeyApp do not confirm success currently and install the app in the background. So the best way to confirm really that the new version of the app is installed is to uninstall the app and install the latest version from HockeyApp. Since you are only uninstalling the app the dependent packages need not be installed again. Please let us know if you face any issues. 

Thanks,
VaijanathA
